export const NavbarMenu=[
    {
        id:1,
        title:"Home",
        link:"/",
    },
    {
        id:2,
        title:"Services",
        link:"/services",
    },
    {
        id:3,
        title:"Gallery",
        link:"/gallery",
    },
    {
        id:4,
        title:"Contact",
        link:"/contact-us",
    }, 
]