export const NavbarMenu=[
    {
        id:1,
        title:"Home",
        link:"/",
    },
    {
        id:2,
        title:"Services",
        link:"/services",
    },
    {
        id:3,
        title:"Gallery",
        link:"/gallery",
    },
    {
        id:4,
        title:"Booking",
        link:"/booking",
    },
    {
        id:5,
        title:"Contact",
        link:"/contact-us",
    },    
    {
        id:6,
        title:"Find Store",
        link:"/find-store",
    },    
]